### ISSUE TITLE
Pycharm 2020 (marked as broken).

### ISSUE THREAD

**Issue by pymen** [galonsky/pycharm_copy_as_import#2]
Plugin Error: Plugin "Copy as Import" is incompatible (until build 193.SNAPSHOT < PY-201.6668.115).<p/>Plugin "Symbols for JavaScript" is incompatible (marked as broken).

**Comment by galonsky** [comment]
this should be fixed as of https://github.com/galonsky/pycharm_copy_as_import/releases/tag/0.0.3
